use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

target 'iOSUI_Example' do
  pod 'iOSUI', :path => '../'

  target 'iOSUI_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots' 
  end
end
