use_frameworks!
inhibit_all_warnings!

target 'iOSUI_Example' do
  pod 'iOSUI', :path => '../'

  target 'iOSUI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
