default_platform(:ios)

platform :ios do
  desc "build debug configuration"
  lane :build_debug do
	build_app(scheme: "iOSUI-Example", 
		workspace: "Example/iOSUI.xcworkspace", 
		include_bitcode: true,
		skip_codesigning: true,
		skip_archive: true)
  end
end
